---
- name: Disable Queue Range
  solace_queue:
    name: "{{item.0.name+'%d' | format(item.1) }}"
    msg_vpn: "{{item.0.msg_vpn}}"
    settings:
      accessType: "{{item.0.accessType | default(omit)}}"
      deadMsgQueue: "{{item.0.deadMsgQueue | default(omit)}}"
      egressEnabled: false
      ingressEnabled: "{{item.0.ingressEnabled | default(omit)}}"
      maxBindCount: "{{item.0.maxBindCount | default(omit)}}"
      maxMsgSize: "{{item.0.maxMsgSize | default(omit)}}"
      maxMsgSpoolUsage: "{{item.0.maxMsgSpoolUsage | default(omit)}}"
      maxRedeliveryCount: "{{item.0.maxRedeliveryCount | default(omit)}}"
      maxTtl: "{{item.0.maxTtl | default(omit)}}"
      owner: "{{item.0.owner | default('')}}"
      permission: "{{item.0.permission | default(omit)}}"
      respectTtlEnabled: "{{item.0.respectTtlEnabled | default(omit)}}"
    state: "{{item.0.state | default('present')}}"
  when: padding == 0
  loop: "{{ queues | product(range(start_number, end_number + 1, stride))|list }}"
  # loop: "{{ queues | product(range(start_number, end_number + 1))|list }}"
  # register: q_output

- name: Disable Queue Range 3 Padding
  solace_queue:
    name: "{{item.0.name+'%03d' | format(item.1) }}"
    msg_vpn: "{{item.0.msg_vpn}}"
    settings:
      accessType: "{{item.0.accessType | default(omit)}}"
      deadMsgQueue: "{{item.0.deadMsgQueue | default(omit)}}"
      egressEnabled: false
      ingressEnabled: "{{item.0.ingressEnabled | default(omit)}}"
      maxBindCount: "{{item.0.maxBindCount | default(omit)}}"
      maxMsgSize: "{{item.0.maxMsgSize | default(omit)}}"
      maxMsgSpoolUsage: "{{item.0.maxMsgSpoolUsage | default(omit)}}"
      maxRedeliveryCount: "{{item.0.maxRedeliveryCount | default(omit)}}"
      maxTtl: "{{item.0.maxTtl | default(omit)}}"
      owner: "{{item.0.owner | default(omit)}}"
      permission: "{{item.0.permission | default(omit)}}"
      respectTtlEnabled: "{{item.0.respectTtlEnabled | default(omit)}}"
    state: "{{item.0.state | default('present')}}"
  when: padding == 3
  loop: "{{ queues | product(range(start_number, end_number + 1, stride))|list }}"
  # loop: "{{ queues | product(range(start_number, end_number + 1))|list }}"
  # register: q_output

# - name: Queue Range Result
#   debug:
#     msg: "{{ item }}"
#   loop: "{{ q_output.results }}"
