---
- name: Queue Subscription
  solace_queue_subscription:
    msg_vpn: "{{item.0.msg_vpn}}"
    queue: "{{item.0.name+'%d' | format(item.1) }}"
    topic: "{{item.0.subscription_topic_prefix+'%03d' | format(item.1) }}"
  when: padding == 0 and item.0.subscription_topic_prefix is defined and ((item.0.state is undefined) or (item.0.state is defined and item.0.state != "absent"))
  loop: "{{queues | product(range(start_number, end_number + 1, stride))|list }}"
  # loop: "{{queues | product(range(start_number, end_number + 1))|list }}"
  register: qs_output

- name: Queue Subscription 3 Padding
  solace_queue_subscription:
    msg_vpn: "{{item.0.msg_vpn}}"
    queue: "{{item.0.name+'%03d' | format(item.1) }}"
    topic: "{{item.0.subscription_topic_prefix+'%03d' | format(item.1) }}"
  when: padding == 3 and item.0.subscription_topic_prefix is defined and ((item.0.state is undefined) or (item.0.state is defined and item.0.state != "absent"))
  loop: "{{queues | product(range(start_number, end_number + 1, stride))|list }}"
  # loop: "{{queues | product(range(start_number, end_number + 1))|list }}"
  register: qs_output

- name: Queue Subscription Result
  debug:
    msg: "{{ item }}"
  loop: "{{ qs_output.results }}"