---
- name: JNDI Queue
  solace_jndi_queue:
    name: "{{item.name}}"
    msg_vpn: "{{item.msg_vpn}}"
    settings:
      physicalName: "{{item.physicalName | default(omit)}}"
    state: "{{item.state | default('present')}}"
  loop: "{{jndi_queues}}"
  register: jndi_queue_output

- name: JNDI Queue Result
  debug:
    msg: "{{ item }}"
  loop: "{{ jndi_queue_output.results }}"
