---
- name: Set Object Name
  set_fact:
    output_object: vpns

- name: "Get {{ output_object }}"
  solace_get_vpns:
    query_params:
        where:
          - "msgVpnName=={{ msg_vpn | default('*') }}"
  register: result

- name: Export {{ output_object }}
  template:
    src: "result-csv.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.yml' ) }}"
  register: result_out

- name: Export Result
  debug:
    msg: "{{ result_out }}}}"
