---
- name: Get VPNs
  solace_get_vpns:
    query_params:
        where:
          - "msgVpnName!=#*"
  register: result

- name: Set Object Name
  set_fact:
    output_object: vpns

- name: Export VPNs
  template:
    src: "result.j2"
    dest: "{{ result_output | default(input_file +'_result.yml' ) }}"
  register: result_out

- name: Export Result
  debug:
    msg: "{{ result_out }}"
