---
- name: Topic Endpoint
  solace_topic_endpoint:
    name: "{{item.name}}"
    msg_vpn: "{{item.msg_vpn}}"
    settings:
      accessType: "{{item.accessType | default(omit)}}"
      consumerAckPropagationEnabled: "{{item.consumerAckPropagationEnabled | default(omit)}}"
      deadMsgQueue: "{{item.deadMsgQueue | default(omit)}}"
      deliveryCountEnabled: "{{item.deliveryCountEnabled | default(omit)}}"
      deliveryDelay: "{{item.deliveryDelay | default(omit)}}"
      egressEnabled: "{{item.egressEnabled | default(omit)}}"
      ingressEnabled: "{{item.ingressEnabled | default(omit)}}"
      maxBindCount: "{{item.maxBindCount | default(omit)}}"
      maxDeliveredUnackedMsgsPerFlow: "{{item.maxDeliveredUnackedMsgsPerFlow | default(omit)}}"
      maxMsgSize: "{{item.maxMsgSize | default(omit)}}"
      maxSpoolUsage: "{{item.maxSpoolUsage | default(omit)}}"
      maxRedeliveryCount: "{{item.maxRedeliveryCount | default(omit)}}"
      maxTtl: "{{item.maxTtl | default(omit)}}"
      owner: "{{item.owner | default(omit)}}"
      permission: "{{item.permission | default(omit)}}"
      redeliveryEnabled: "{{item.redeliveryEnabled | default(omit)}}"
      rejectLowPriorityMsgEnabled: "{{item.rejectLowPriorityMsgEnabled | default(omit)}}"
      rejectLowPriorityMsgLimit: "{{item.rejectLowPriorityMsgLimit | default(omit)}}"
      rejectMsgToSenderOnDiscardBehavior: "{{item.rejectMsgToSenderOnDiscardBehavior | default(omit)}}"
      respectMsgPriorityEnabled: "{{item.respectMsgPriorityEnabled | default(omit)}}"
      respectTtlEnabled: "{{item.respectTtlEnabled | default(omit)}}"
    state: "{{item.state | default('present')}}"
  loop: "{{topic_endpoints}}"
  register: te_output

- name: Topic Endpoint Result
  debug:
    msg: "{{ item }}"
  loop: "{{ te_output.results }}"

