---
- name: Create, Update Internal Link at Local Broker
  block:
  - name: Create/Update Internal Link (Local)
    solace_dmr_cluster_link:
      dmr_cluster_name: "{{ current_dmr.result_list.0.data.dmrClusterName }}"
      remote_node_name: "{{ hostvars[item].current_dmr.result_list.0.data.nodeName }}"
      settings:
        authenticationBasicPassword: "{{ hostvars[item].cluster_password | default(omit) }}"
        authenticationScheme: "{{ cluster_link_authenticationScheme | default(omit) }}"
        enabled: false
        initiator: "{{ cluster_link_initiator | default(omit) }}"
        span: internal
        transportCompressedEnabled: "{{ cluster_link_transportCompressedEnabled | default(omit) }}"
        transportTlsEnabled: "{{ cluster_link_transportTlsEnabled | default(omit) }}"
    loop: "{{ groups['internal_link'] }}"
  - name: Add Internal Link Remote Address (Local)
    solace_dmr_cluster_link_remote_address:
      dmr_cluster_name: "{{ current_dmr.result_list.0.data.dmrClusterName }}"
      remote_node_name: "{{ hostvars[item].current_dmr.result_list.0.data.nodeName }}"
      remote_address: "{{ hostvars[item].cluster_link_service_address }}:{{ hostvars[item].cluster_link_service_port }}"
    loop: "{{ groups['internal_link'] }}"
  - name: Enable Internal Link (Local)
    solace_dmr_cluster_link:
      dmr_cluster_name: "{{ current_dmr.result_list.0.data.dmrClusterName }}"
      remote_node_name: "{{ hostvars[item].current_dmr.result_list.0.data.nodeName }}"
      settings:
        enabled: true
    loop: "{{ groups['internal_link'] }}"
  - name: Create/Update DMR Bridge (Local)
    solace_dmr_bridge:
      msg_vpn: "{{cluster_link_msg_vpn}}"
      remote_node_name: "{{ hostvars[item].current_dmr.result_list.0.data.nodeName }}"
      settings:
        remoteMsgVpnName: "{{hostvars[item].cluster_link_msg_vpn}}"
    loop: "{{ groups['internal_link'] }}"
  when: ("local" in group_names and (cluster_link_state is not defined or cluster_link_state != "absent"))

- name: Create, Update Internal Link at Remote Broker
  block: 
  - name: Create/Update Internal Link (Remote)
    solace_dmr_cluster_link:
      dmr_cluster_name: "{{ current_dmr.result_list.0.data.dmrClusterName }}"
      remote_node_name: "{{ hostvars[item].current_dmr.result_list.0.data.nodeName }}"
      settings:
        authenticationBasicPassword: "{{ hostvars[item].cluster_password | default(omit) }}"
        authenticationScheme: "{{ hostvars[item].cluster_link_authenticationScheme | default(omit) }}"
        enabled: false
        initiator: "{{ 'remote' if hostvars[item].cluster_link_initiator=='local' else 'local' if hostvars[item].cluster_link_initiator=='remote' else 'lexical' }}"
        span: internal
        transportCompressedEnabled: "{{ hostvars[item].cluster_link_transportCompressedEnabled | default(omit) }}"
        transportTlsEnabled: "{{ hostvars[item].cluster_link_transportTlsEnabled | default(omit) }}"
    loop: "{{ groups['local'] }}"
  - name: Enable Internal Link (Remote)
    solace_dmr_cluster_link:
      dmr_cluster_name: "{{ current_dmr.result_list.0.data.dmrClusterName }}"
      remote_node_name: "{{ hostvars[item].current_dmr.result_list.0.data.nodeName }}"
      settings:
        enabled: "{{ hostvars[item].cluster_link_enabled | default(omit) }}"
    loop: "{{ groups['local'] }}"
  - name: Create/Update DMR Bridge (Remote)
    solace_dmr_bridge:
      msg_vpn: "{{ cluster_link_msg_vpn }}"
      remote_node_name: "{{ hostvars[item].current_dmr.result_list.0.data.nodeName }}"
      settings:
        remoteMsgVpnName: "{{hostvars[item].cluster_link_msg_vpn}}"
    loop: "{{ groups['local'] }}"
  when: ("internal_link" in group_names and (hostvars[item].cluster_link_state is not defined or hostvars[item].cluster_link_state != "absent"))

- name: Delete Internal Link at Local Broker
  block:
  - name: Delete Internal Link (Local)
    solace_dmr_cluster_link:
      dmr_cluster_name: "{{ current_dmr.result_list.0.data.dmrClusterName }}"
      remote_node_name: "{{ hostvars[item].current_dmr.result_list.0.data.nodeName }}"
      state: "{{ cluster_link_state }}"
    loop: "{{ groups['internal_link'] }}"
  - name: Delete DMR Bridge (Local)
    solace_dmr_bridge:
      msg_vpn: "{{cluster_link_msg_vpn}}"
      remote_node_name: "{{ hostvars[item].current_dmr.result_list.0.data.nodeName }}"
      state: "{{ cluster_link_state }}"
    loop: "{{ groups['internal_link'] }}"
  when: ("local" in group_names and cluster_link_state is defined and cluster_link_state == "absent")

- name: Delete Internal Link at Remote Broker
  block:
  - name: Delete Internal Link (Local)
    solace_dmr_cluster_link:
      dmr_cluster_name: "{{ current_dmr.result_list.0.data.dmrClusterName }}"
      remote_node_name: "{{ hostvars[item].current_dmr.result_list.0.data.nodeName }}"
      state: "{{ hostvars[item].cluster_link_state }}"
    loop: "{{ groups['local'] }}"
  - name: Delete DMR Bridge (Remote)
    solace_dmr_bridge:
      msg_vpn: "{{ cluster_link_msg_vpn }}"
      remote_node_name: "{{ hostvars[item].current_dmr.result_list.0.data.nodeName }}"
      state: "{{ hostvars[item].cluster_link_state }}"
    loop: "{{ groups['local'] }}"
  when: ("internal_link" in group_names and hostvars[item].cluster_link_state is defined and hostvars[item].cluster_link_state == "absent")
