---
- name: Cloud Client Profile
  solace_cloud_client_profile:
    name: "{{item.name}}"
    #msg_vpn: "{{item.msg_vpn}}"
    settings:
      allowGuaranteedEndpointCreateDurability: "{{item.allowGuaranteedEndpointCreateDurability | default(omit)}}"
      allowGuaranteedEndpointCreateEnabled: "{{item.allowGuaranteedEndpointCreateEnabled | default(omit)}}"
      allowGuaranteedMsgSendEnabled: "{{item.allowGuaranteedMsgSendEnabled | default(omit)}}"
      allowGuaranteedMsgReceiveEnabled: "{{item.allowGuaranteedMsgReceiveEnabled | default(omit)}}"
      allowBridgeConnectionsEnabled: "{{item.allowBridgeConnectionsEnabled | default(omit)}}"
      allowSharedSubscriptionsEnabled: "{{item.allowSharedSubscriptionsEnabled | default(omit)}}"
      allowTransactedSessionsEnabled: "{{item.allowTransactedSessionsEnabled | default(omit)}}"
      tlsAllowDowngradeToPlainTextEnabled: "{{item.tlsAllowDowngradeToPlainTextEnabled | default(omit)}}"
      apiQueueManagementCopyFromOnCreateTemplateName: "{{item.apiQueueManagementCopyFromOnCreateTemplateName | default(omit)}}"
      apiTopicEndpointManagementCopyFromOnCreateTemplateName: "{{item.apiTopicEndpointManagementCopyFromOnCreateTemplateName | default(omit)}}"
      compressionEnabled: "{{item.compressionEnabled | default(omit)}}"
      elidingDelay: "{{item.elidingDelay | default(omit)}}"
      elidingEnabled: "{{item.elidingEnabled | default(omit)}}"
      maxConnectionCountPerClientUsername: "{{item.maxConnectionCountPerClientUsername | default(omit)}}"
      maxEgressFlowCount: "{{item.maxEgressFlowCount | default(omit)}}"
      maxEndpointCountPerClientUsername: "{{item.maxEndpointCountPerClientUsername | default(omit)}}"
      maxIngressFlowCount: "{{item.maxIngressFlowCount | default(omit)}}"
      maxMsgsPerTransaction: "{{item.maxMsgsPerTransaction | default(omit)}}"
      maxSubscriptionCount: "{{item.maxSubscriptionCount | default(omit)}}"
      maxTransactedSessionCount: "{{item.maxTransactedSessionCount | default(omit)}}"
      maxTransactionCount: "{{item.maxTransactionCount | default(omit)}}"
      rejectMsgToSenderOnNoSubscriptionMatchEnabled: "{{item.rejectMsgToSenderOnNoSubscriptionMatchEnabled | default(omit)}}"
      replicationAllowClientConnectWhenStandbyEnabled: "{{item.replicationAllowClientConnectWhenStandbyEnabled | default(omit)}}"
      serviceMinKeepaliveTimeout: "{{item.serviceMinKeepaliveTimeout | default(omit)}}"
      serviceSmfMaxConnectionCountPerClientUsername: "{{item.serviceSmfMaxConnectionCountPerClientUsername | default(omit)}}"
      serviceSmfMinKeepaliveEnabled: "{{item.serviceSmfMinKeepaliveEnabled | default(omit)}}"
      serviceWebInactiveTimeout: "{{item.serviceWebInactiveTimeout | default(omit)}}"
      serviceWebMaxConnectionCountPerClientUsername: "{{item.serviceWebMaxConnectionCountPerClientUsername | default(omit)}}"
      serviceWebMaxPayload: "{{item.serviceWebMaxPayload | default(omit)}}"
      tcpCongestionWindowSize: "{{item.tcpCongestionWindowSize | default(omit)}}"
      tcpKeepaliveCount: "{{item.tcpKeepaliveCount | default(omit)}}"
      tcpKeepaliveIdleTime: "{{item.tcpKeepaliveIdleTime | default(omit)}}"
      tcpKeepaliveInterval: "{{item.tcpKeepaliveInterval | default(omit)}}"
      tcpMaxSegmentSize: "{{item.tcpMaxSegmentSize | default(omit)}}"
      tcpMaxWindowSize: "{{item.tcpMaxWindowSize | default(omit)}}"
    state: "{{item.state | default('present')}}"
  loop: "{{client_profiles}}"
  register: ccp_output

- name: Cloud Client Profile Result
  debug:
    msg: "{{ item }}"
  loop: "{{ ccp_output.results }}"