---
- name: Cloud Client Profile
  solace_cloud_client_profile:
    name: "{{item.name}}"
    #msg_vpn: "{{item.msg_vpn}}"
    settings:
      allowGuaranteedEndpointCreateDurability: "{{item.allowGuaranteedEndpointCreateDurability | default(omit)}}"
      allowGuaranteedEndpointCreateEnabled: "{{item.allowGuaranteedEndpointCreateEnabled | default(omit)}}"
      allowGuaranteedMsgSendEnabled: "{{item.allowGuaranteedMsgSendEnabled | default(omit)}}"
      allowGuaranteedMsgReceiveEnabled: "{{item.allowGuaranteedMsgReceiveEnabled | default(omit)}}"
      allowBridgeConnectionsEnabled: "{{item.allowBridgeConnectionsEnabled | default(omit)}}"
      allowSharedSubscriptionsEnabled: "{{item.allowSharedSubscriptionsEnabled | default(omit)}}"
      allowTransactedSessionsEnabled: "{{item.allowTransactedSessionsEnabled | default(omit)}}"
      tlsAllowDowngradeToPlainTextEnabled: "{{item.tlsAllowDowngradeToPlainTextEnabled | default(omit)}}"
    state: "{{item.state | default('present')}}"
  loop: "{{client_profiles}}"
  register: ccp_output

- name: Cloud Client Profile Result
  debug:
    msg: "{{ item }}"
  loop: "{{ ccp_output.results }}"