---
- name: Create, Update, Delete Client Profile
  import_tasks: client-profile.yml
  when: broker_type != "solace_cloud"

- name: Create, Update, Delete Cloud Client Profile
  import_tasks: cloud-client-profile.yml
  when: broker_type == "solace_cloud"