---
- name: Create, Update, Delete VPN
  solace_vpn:
    name: "{{ item.msg_vpn }}"
    settings:
      authenticationBasicEnabled: "{{ item.authenticationBasicEnabled | default(omit) }}"
      authenticationBasicType: "{{ item.authenticationBasicType | default(omit) }}"
      authenticationBasicProfileName: "{{ item.authenticationBasicProfileName | default(omit) }}"
      authenticationClientCertEnabled: "{{ item.authenticationClientCertEnabled | default(omit) }}"
      authorizationProfileName: "{{ item.authorizationProfileName | default(omit) }}"
      authorizationType: "{{ item.authorizationType | default(omit) }}"
      dmrEnabled: "{{ item.dmrEnabled | default(omit) }}"
      enabled: "{{ item.enabled | default(omit) }}"
      eventLargeMsgTreshold: "{{ item.eventLargeMsgTreshold | default(omit) }}"
      eventLogTag: "{{ item.eventLogTag | default(omit) }}"
      jndiEnabled: "{{ item.jndiEnabled | default(omit) }}"
      maxConnectionCount: "{{ item.maxConnectionCount | default(omit) }}"
      maxEndpointCount: "{{ item.maxEndpointCount | default(omit) }}"
      maxMsgSpoolUsage: "{{ item.maxMsgSpoolUsage | default(omit) }}"
      mqttRetainMaxMemory: "{{ item.mqttRetainMaxMemory | default(omit) }}"
      replicationAckPropagationIntervalMsgCount: "{{ item.replicationAckPropagationIntervalMsgCount | default(omit) }}"
      replicationBridgeAuthenticationBasicClientUsername: "{{ item.replicationBridgeAuthenticationBasicClientUsername | default(omit) }}"
      replicationBridgeAuthenticationBasicPassword: "{{ item.replicationBridgeAuthenticationBasicPassword | default(omit) }}"
      replicationBridgeAuthenticationClientCertContent: "{{ item.replicationBridgeAuthenticationClientCertContent | default(omit) }}"
      replicationBridgeAuthenticationClientCertPassword: "{{ item.replicationBridgeAuthenticationClientCertPassword | default(omit) }}"
      replicationBridgeAuthenticationScheme: "{{ item.replicationBridgeAuthenticationScheme | default(omit) }}"
      replicationBridgeCompressedDataEnabled: "{{ item.replicationBridgeCompressedDataEnabled | default(omit) }}"
      replicationBridgeEgressFlowWindowSize: "{{ item.replicationBridgeEgressFlowWindowSize | default(omit) }}"
      replicationBridgeRetryDelay: "{{ item.replicationBridgeRetryDelay | default(omit) }}"
      replicationBridgeTlsEnabled: "{{ item.replicationBridgeTlsEnabled | default(omit) }}"
      replicationBridgeUnidirectionalClientProfileName: "{{ item.replicationBridgeUnidirectionalClientProfileName | default(omit) }}"
      replicationEnabled: "{{ item.replicationEnabled | default(omit) }}"
      replicationEnabledQueueBehavior: "{{ item.replicationEnabledQueueBehavior | default(omit) }}"
      replicationQueueMaxMsgSpoolUsage: "{{ item.replicationQueueMaxMsgSpoolUsage | default(omit) }}"
      replicationQueueRejectMsgToSenderOnDiscardEnabled: "{{ item.replicationQueueRejectMsgToSenderOnDiscardEnabled | default(omit) }}"
      replicationRejectMsgWhenSyncIneligibleEnabled: "{{ item.replicationRejectMsgWhenSyncIneligibleEnabled | default(omit) }}"
      replicationRole: "{{ item.replicationRole | default(omit) }}"
      replicationTransactionMode: "{{ item.replicationTransactionMode | default(omit) }}"
      serviceAmqpPlainTextEnabled: "{{ item.serviceAmqpPlainTextEnabled | default(omit) }}"
      serviceAmqpPlainTextListenPort: "{{ item.serviceAmqpPlainTextListenPort | default(omit) }}"
      serviceAmqpTlsEnabled: "{{ item.serviceAmqpTlsEnabled | default(omit) }}"
      serviceAmqpTlsListenPort: "{{ item.serviceAmqpTlsListenPort | default(omit) }}"
      serviceMqttPlainTextEnabled: "{{ item.serviceMqttPlainTextEnabled | default(omit) }}"
      serviceMqttPlainTextListenPort: "{{ item.serviceMqttPlainTextListenPort | default(omit) }}"
      serviceMqttTlsEnabled: "{{ item.serviceMqttTlsEnabled | default(omit) }}"
      serviceMqttTlsListenPort: "{{ item.serviceMqttTlsListenPort | default(omit) }}"
      serviceMqttWebSocketEnabled: "{{ item.serviceMqttWebSocketEnabled | default(omit) }}"
      serviceMqttWebSocketListenPort: "{{ item.serviceMqttWebSocketListenPort | default(omit) }}"
      serviceMqttTlsWebSocketEnabled: "{{ item.serviceMqttTlsWebSocketEnabled | default(omit) }}"
      serviceMqttTlsWebSocketListenPort: "{{ item.serviceMqttTlsWebSocketListenPort | default(omit) }}"
      serviceRestIncomingPlainTextEnabled: "{{ item.serviceRestIncomingPlainTextEnabled | default(omit) }}"
      serviceRestIncomingPlainTextListenPort: "{{ item.serviceRestIncomingPlainTextListenPort | default(omit) }}"
      serviceRestIncomingTlsEnabled: "{{ item.serviceRestIncomingTlsEnabled | default(omit) }}"
      serviceRestIncomingTlsListenPort: "{{ item.serviceRestIncomingTlsListenPort | default(omit) }}"
      serviceRestMode: "{{ item.serviceRestMode | default(omit) }}"
      serviceSmfPlainTextEnabled: "{{ item.serviceSmfPlainTextEnabled | default(omit) }}"
      serviceSmfTlsEnabled: "{{ item.serviceSmfTlsEnabled | default(omit) }}"
      serviceWebPlainTextEnabled: "{{ item.serviceWebPlainTextEnabled | default(omit) }}"
      serviceWebTlsEnabled: "{{ item.serviceWebTlsEnabled | default(omit) }}"
      tlsAllowDowngradeToPlainTextEnabled: "{{ item.tlsAllowDowngradeToPlainTextEnabled | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ vpns }}"
  register: v_output

- name: VPN Result
  debug:
    msg: "{{ item }}"
  loop: "{{ v_output.results }}"
