---
- name: Create, Update, Delete VPN
  solace_vpn:
    name: "{{ item.msg_vpn }}"
    settings:
      alias: "{{ item.alias | default(omit) }}"
      authenticationBasicEnabled: "{{ item.authenticationBasicEnabled | default(omit) }}"
      authenticationBasicType: "{{ item.authenticationBasicType | default(omit) }}"
      authenticationBasicProfileName: "{{ item.authenticationBasicProfileName | default(omit) }}"
      authenticationBasicRadiusDomain: "{{ item.authenticationBasicRadiusDomain | default(omit) }}"
      authenticationClientCertEnabled: "{{ item.authenticationClientCertEnabled | default(omit) }}"
      authenticationClientCertAllowApiProvidedUsernameEnabled: "{{ item.authenticationClientCertAllowApiProvidedUsernameEnabled | default(omit) }}"
      authenticationClientCertCertificateMatchingRulesEnabled: "{{ item.authenticationClientCertCertificateMatchingRulesEnabled | default(omit) }}"
      authenticationClientCertMaxChainDepth: "{{ item.authenticationClientCertMaxChainDepth | default(omit) }}"
      authenticationClientCertRevocationCheckMode: "{{ item.authenticationClientCertRevocationCheckMode | default(omit) }}"
      authenticationClientCertUsernameSource: "{{ item.authenticationClientCertUsernameSource | default(omit) }}"
      authenticationClientCertValidateDateEnabled: "{{ item.authenticationClientCertValidateDateEnabled | default(omit) }}"
      authenticationKerberosAllowApiProvidedUsernameEnabled: "{{ item.authenticationKerberosAllowApiProvidedUsernameEnabled | default(omit) }}"
      authenticationKerberosEnabled: "{{ item.authenticationKerberosEnabled | default(omit) }}"
      authenticationOauthDefaultProfileName: "{{ item.authenticationOauthDefaultProfileName | default(omit) }}"
      authenticationOauthDefaultProviderName: "{{ item.authenticationOauthDefaultProviderName | default(omit) }}"
      authenticationOauthEnabled: "{{ item.authenticationOauthEnabled | default(omit) }}"
      authorizationLdapGroupMembershipAttributeName: "{{ item.authorizationLdapGroupMembershipAttributeName | default(omit) }}"
      authorizationLdapTrimClientUsernameDomainEnabled: "{{ item.authorizationLdapTrimClientUsernameDomainEnabled | default(omit) }}"
      authorizationProfileName: "{{ item.authorizationProfileName | default(omit) }}"
      authorizationType: "{{ item.authorizationType | default(omit) }}"
      bridgingTlsServerCertEnforceTrustedCommonNameEnabled: "{{ item.bridgingTlsServerCertEnforceTrustedCommonNameEnabled | default(omit) }}"
      bridgingTlsServerCertMaxChainDepth: "{{ item.bridgingTlsServerCertMaxChainDepth | default(omit) }}"
      bridgingTlsServerCertValidateDateEnabled: "{{ item.bridgingTlsServerCertValidateDateEnabled | default(omit) }}"
      bridgingTlsServerCertValidateNameEnabled: "{{ item.bridgingTlsServerCertValidateNameEnabled | default(omit) }}"
      distributedCacheManagementEnabled: "{{ item.distributedCacheManagementEnabled | default(omit) }}"
      dmrEnabled: "{{ item.dmrEnabled | default(omit) }}"
      enabled: "{{ item.enabled | default(omit) }}"
      eventLargeMsgTreshold: "{{ item.eventLargeMsgTreshold | default(omit) }}"
      eventLogTag: "{{ item.eventLogTag | default(omit) }}"
      eventPublishClientEnabled: "{{ item.eventPublishClientEnabled | default(omit) }}"
      eventPublishMsgVpnEnabled: "{{ item.eventPublishMsgVpnEnabled | default(omit) }}"
      eventPublishSubscriptionMode: "{{ item.eventPublishSubscriptionMode | default(omit) }}"
      eventPublishTopicFormatMqttEnabled: "{{ item.eventPublishTopicFormatMqttEnabled | default(omit) }}"
      eventPublishTopicFormatSmfEnabled: "{{ item.eventPublishTopicFormatSmfEnabled | default(omit) }}"
      exportSubscriptionsEnabled: "{{ item.exportSubscriptionsEnabled | default(omit) }}"
      jndiEnabled: "{{ item.jndiEnabled | default(omit) }}"
      maxConnectionCount: "{{ item.maxConnectionCount | default(omit) }}"
      maxEgressFlowCount: "{{ item.maxEgressFlowCount | default(omit) }}"
      maxEndpointCount: "{{ item.maxEndpointCount | default(omit) }}"
      maxIngressFlowCount: "{{ item.maxIngressFlowCount | default(omit) }}"
      maxMsgSpoolUsage: "{{ item.maxMsgSpoolUsage | default(omit) }}"
      maxSubscriptionCount: "{{ item.maxSubscriptionCount | default(omit) }}"
      maxTransactedSessionCount: "{{ item.maxTransactedSessionCount | default(omit) }}"
      maxTransactionCount: "{{ item.maxTransactionCount | default(omit) }}"
      mqttRetainMaxMemory: "{{ item.mqttRetainMaxMemory | default(omit) }}"
      preferIpVersion: "{{ item.preferIpVersion | default(omit) }}"
      replicationAckPropagationIntervalMsgCount: "{{ item.replicationAckPropagationIntervalMsgCount | default(omit) }}"
      replicationBridgeAuthenticationBasicClientUsername: "{{ item.replicationBridgeAuthenticationBasicClientUsername | default(omit) }}"
      replicationBridgeAuthenticationBasicPassword: "{{ item.replicationBridgeAuthenticationBasicPassword | default(omit) }}"
      replicationBridgeAuthenticationClientCertContent: "{{ item.replicationBridgeAuthenticationClientCertContent | default(omit) }}"
      replicationBridgeAuthenticationClientCertPassword: "{{ item.replicationBridgeAuthenticationClientCertPassword | default(omit) }}"
      replicationBridgeAuthenticationScheme: "{{ item.replicationBridgeAuthenticationScheme | default(omit) }}"
      replicationBridgeCompressedDataEnabled: "{{ item.replicationBridgeCompressedDataEnabled | default(omit) }}"
      replicationBridgeEgressFlowWindowSize: "{{ item.replicationBridgeEgressFlowWindowSize | default(omit) }}"
      replicationBridgeRetryDelay: "{{ item.replicationBridgeRetryDelay | default(omit) }}"
      replicationBridgeTlsEnabled: "{{ item.replicationBridgeTlsEnabled | default(omit) }}"
      replicationBridgeUnidirectionalClientProfileName: "{{ item.replicationBridgeUnidirectionalClientProfileName | default(omit) }}"
      replicationEnabled: "{{ item.replicationEnabled | default(omit) }}"
      replicationEnabledQueueBehavior: "{{ item.replicationEnabledQueueBehavior | default(omit) }}"
      replicationQueueMaxMsgSpoolUsage: "{{ item.replicationQueueMaxMsgSpoolUsage | default(omit) }}"
      replicationQueueRejectMsgToSenderOnDiscardEnabled: "{{ item.replicationQueueRejectMsgToSenderOnDiscardEnabled | default(omit) }}"
      replicationRejectMsgWhenSyncIneligibleEnabled: "{{ item.replicationRejectMsgWhenSyncIneligibleEnabled | default(omit) }}"
      replicationRole: "{{ item.replicationRole | default(omit) }}"
      replicationTransactionMode: "{{ item.replicationTransactionMode | default(omit) }}"
      restTlsServerCertEnforceTrustedCommonNameEnabled: "{{ item.restTlsServerCertEnforceTrustedCommonNameEnabled | default(omit) }}"
      restTlsServerCertMaxChainDepth: "{{ item.restTlsServerCertMaxChainDepth | default(omit) }}"
      restTlsServerCertValidateDateEnabled: "{{ item.restTlsServerCertValidateDateEnabled | default(omit) }}"
      restTlsServerCertValidateNameEnabled: "{{ item.restTlsServerCertValidateNameEnabled | default(omit) }}"
      sempOverMsgBusAdminClientEnabled: "{{ item.sempOverMsgBusAdminClientEnabled | default(omit) }}"
      sempOverMsgBusAdminDistributedCacheEnabled: "{{ item.sempOverMsgBusAdminDistributedCacheEnabled | default(omit) }}"
      sempOverMsgBusAdminEnabled: "{{ item.sempOverMsgBusAdminEnabled | default(omit) }}"
      sempOverMsgBusEnabled: "{{ item.sempOverMsgBusEnabled | default(omit) }}"
      sempOverMsgBusLegacyShowClearEnabled: "{{ item.sempOverMsgBusLegacyShowClearEnabled | default(omit) }}"
      sempOverMsgBusShowEnabled: "{{ item.sempOverMsgBusShowEnabled | default(omit) }}"
      serviceAmqpMaxConnectionCount: "{{ item.serviceAmqpMaxConnectionCount | default(omit) }}"
      serviceAmqpPlainTextEnabled: "{{ item.serviceAmqpPlainTextEnabled | default(omit) }}"
      serviceAmqpPlainTextListenPort: "{{ item.serviceAmqpPlainTextListenPort | default(omit) }}"
      serviceAmqpTlsEnabled: "{{ item.serviceAmqpTlsEnabled | default(omit) }}"
      serviceAmqpTlsListenPort: "{{ item.serviceAmqpTlsListenPort | default(omit) }}"
      serviceMqttAuthenticationClientCertRequest: "{{ item.serviceMqttAuthenticationClientCertRequest | default(omit) }}"
      serviceMqttMaxConnectionCount: "{{ item.serviceMqttMaxConnectionCount | default(omit) }}"
      serviceMqttPlainTextEnabled: "{{ item.serviceMqttPlainTextEnabled | default(omit) }}"
      serviceMqttPlainTextListenPort: "{{ item.serviceMqttPlainTextListenPort | default(omit) }}"
      serviceMqttTlsEnabled: "{{ item.serviceMqttTlsEnabled | default(omit) }}"
      serviceMqttTlsListenPort: "{{ item.serviceMqttTlsListenPort | default(omit) }}"
      serviceMqttWebSocketEnabled: "{{ item.serviceMqttWebSocketEnabled | default(omit) }}"
      serviceMqttWebSocketListenPort: "{{ item.serviceMqttWebSocketListenPort | default(omit) }}"
      serviceMqttTlsWebSocketEnabled: "{{ item.serviceMqttTlsWebSocketEnabled | default(omit) }}"
      serviceMqttTlsWebSocketListenPort: "{{ item.serviceMqttTlsWebSocketListenPort | default(omit) }}"
      serviceRestIncomingAuthenticationClientCertRequest: "{{ item.serviceRestIncomingAuthenticationClientCertRequest | default(omit) }}"
      serviceRestIncomingAuthorizationHeaderHandling: "{{ item.serviceRestIncomingAuthorizationHeaderHandling | default(omit) }}"
      serviceRestIncomingMaxConnectionCount: "{{ item.serviceRestIncomingMaxConnectionCount | default(omit) }}"
      serviceRestIncomingPlainTextEnabled: "{{ item.serviceRestIncomingPlainTextEnabled | default(omit) }}"
      serviceRestIncomingPlainTextListenPort: "{{ item.serviceRestIncomingPlainTextListenPort | default(omit) }}"
      serviceRestIncomingTlsEnabled: "{{ item.serviceRestIncomingTlsEnabled | default(omit) }}"
      serviceRestIncomingTlsListenPort: "{{ item.serviceRestIncomingTlsListenPort | default(omit) }}"
      serviceRestMode: "{{ item.serviceRestMode | default(omit) }}"
      serviceRestOutgoingMaxConnectionCount: "{{ item.serviceRestOutgoingMaxConnectionCount | default(omit) }}"
      serviceSmfMaxConnectionCount: "{{ item.serviceSmfMaxConnectionCount | default(omit) }}"
      serviceSmfPlainTextEnabled: "{{ item.serviceSmfPlainTextEnabled | default(omit) }}"
      serviceSmfTlsEnabled: "{{ item.serviceSmfTlsEnabled | default(omit) }}"
      serviceWebAuthenticationClientCertRequest: "{{ item.serviceWebAuthenticationClientCertRequest | default(omit) }}"
      serviceWebMaxConnectionCount: "{{ item.serviceWebMaxConnectionCount | default(omit) }}"
      serviceWebPlainTextEnabled: "{{ item.serviceWebPlainTextEnabled | default(omit) }}"
      serviceWebTlsEnabled: "{{ item.serviceWebTlsEnabled | default(omit) }}"
      tlsAllowDowngradeToPlainTextEnabled: "{{ item.tlsAllowDowngradeToPlainTextEnabled | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ vpns }}"
  register: v_output

- name: VPN Result
  debug:
    msg: "{{ item }}"
  loop: "{{ v_output.results }}"
