---
- name: JNDI CF
  solace_jndi_connection_factory:
    name: "{{item.name}}"
    msg_vpn: "{{item.msg_vpn}}"
    settings:
      transportDirectTransportEnabled: "{{item.transportDirectTransportEnabled | default(omit)}}"
    state: "{{item.state | default('present')}}"
  loop: "{{jndi_cfs}}"
  register: jndi_cf_output

- name: JNDI CF Result
  debug:
    msg: "{{ item }}"
  loop: "{{ jndi_cf_output.results }}"
