---
- name: JNDI CF
  solace_jndi_connection_factory:
    name: "{{item.name}}"
    msg_vpn: "{{item.msg_vpn}}"
    settings:
      allowDuplicateClientIdEnabled: "{{item.allowDuplicateClientIdEnabled | default(omit)}}"
      clientDescription: "{{item.clientDescription | default(omit)}}"
      clientId: "{{item.clientId | default(omit)}}"
      dtoReceiveOverrideEnabled: "{{item.dtoReceiveOverrideEnabled | default(omit)}}"
      dtoReceiveSubscriberLocalPriority: "{{item.dtoReceiveSubscriberLocalPriority | default(omit)}}"
      dtoReceiveSubscriberNetworkPriority: "{{item.dtoReceiveSubscriberNetworkPriority | default(omit)}}"
      dtoSendEnabled: "{{item.dtoSendEnabled | default(omit)}}"
      dynamicEndpointCreateDurableEnabled: "{{item.dynamicEndpointCreateDurableEnabled | default(omit)}}"
      dynamicEndpointRespectTtlEnabled: "{{item.dynamicEndpointRespectTtlEnabled | default(omit)}}"
      guaranteedReceiveAckTimeout: "{{item.guaranteedReceiveAckTimeout | default(omit)}}"
      guaranteedReceiveReconnectRetryCount: "{{item.guaranteedReceiveReconnectRetryCount | default(omit)}}"
      guaranteedReceiveReconnectRetryWait: "{{item.guaranteedReceiveReconnectRetryWait | default(omit)}}"
      guaranteedReceiveWindowSize: "{{item.guaranteedReceiveWindowSize | default(omit)}}"
      guaranteedReceiveWindowSizeAckThreshold: "{{item.guaranteedReceiveWindowSizeAckThreshold | default(omit)}}"
      guaranteedSendAckTimeout: "{{item.guaranteedSendAckTimeout | default(omit)}}"
      guaranteedSendWindowSize: "{{item.guaranteedSendWindowSize | default(omit)}}"
      messagingDefaultDeliveryMode: "{{item.messagingDefaultDeliveryMode | default(omit)}}"
      messagingDefaultDmqEligibleEnabled: "{{item.messagingDefaultDmqEligibleEnabled | default(omit)}}"
      messagingDefaultElidingEligibleEnabled: "{{item.messagingDefaultElidingEligibleEnabled | default(omit)}}"
      messagingJmsxUserIdEnabled: "{{item.messagingJmsxUserIdEnabled | default(omit)}}"
      messagingTextInXmlPayloadEnabled: "{{item.messagingTextInXmlPayloadEnabled | default(omit)}}"
      transportCompressionLevel: "{{item.transportCompressionLevel | default(omit)}}"
      transportConnectRetryCount: "{{item.transportConnectRetryCount | default(omit)}}"
      transportConnectRetryPerHostCount: "{{item.transportConnectRetryPerHostCount | default(omit)}}"
      transportConnectTimeout: "{{item.transportConnectTimeout | default(omit)}}"
      transportDirectTransportEnabled: "{{item.transportDirectTransportEnabled | default(omit)}}"
      transportKeepaliveCount: "{{item.transportKeepaliveCount | default(omit)}}"
      transportKeepaliveEnabled: "{{item.transportKeepaliveEnabled | default(omit)}}"
      transportKeepaliveInterval: "{{item.transportKeepaliveInterval | default(omit)}}"
      transportMsgCallbackOnIoThreadEnabled: "{{item.transportMsgCallbackOnIoThreadEnabled | default(omit)}}"
      transportOptimizeDirectEnabled: "{{item.transportOptimizeDirectEnabled | default(omit)}}"
      transportPort: "{{item.transportPort | default(omit)}}"
      transportReadTimeout: "{{item.transportReadTimeout | default(omit)}}"
      transportReceiveBufferSize: "{{item.transportReceiveBufferSize | default(omit)}}"
      transportReconnectRetryCount: "{{item.transportReconnectRetryCount | default(omit)}}"
      transportReconnectRetryWait: "{{item.transportReconnectRetryWait | default(omit)}}"
      transportSendBufferSize: "{{item.transportSendBufferSize | default(omit)}}"
      transportTcpNoDelayEnabled: "{{item.transportTcpNoDelayEnabled | default(omit)}}"
      xaEnabled: "{{item.xaEnabled | default(omit)}}"
    state: "{{item.state | default('present')}}"
  loop: "{{jndi_cfs}}"
  register: jndi_cf_output

- name: JNDI CF Result
  debug:
    msg: "{{ item }}"
  loop: "{{ jndi_cf_output.results }}"
