---
- name: Disable Bridge
  import_tasks: disable_bridge.yml
  tags:
  - change_authentication

- name: Create, Update, Delete Bridge
  import_tasks: bridge.yml

- name: Bridge Remote VPN
  import_tasks: bridge-remote-vpn.yml

- name: Bridge Remote Subscription List
  import_tasks: bridge-remote-subscription-list.yml


