---
- name: Set Object Name
  set_fact:
    output_object: bridges

- name: "Get {{ output_object }}"
  solace_get_bridges:
    msg_vpn: "{{msg_vpn}}"
    query_params:
        where:
          - "bridgeName!=#*"
          - "bridgeName=={{ search_filter | default('*')}}"
  register: result

- name: "Get Remote Message VPNs"
  solace_get_bridge_remote_vpns:
    msg_vpn: "{{msg_vpn}}"
    bridge_name: "{{item.data.bridgeName}}"
  loop: "{{ result.result_list }}"
  register: bridge_remote_vpns

- name: "Get Remote Subscriptions"
  solace_get_bridge_remote_subscriptions:
    msg_vpn: "{{msg_vpn}}"
    bridge_name: "{{item.data.bridgeName}}"
  loop: "{{ result.result_list | rejectattr('data', '==',{}) | list }}"
  register: bridge_remote_subscriptions

- name: Export {{ output_object }}
  template:
    src: "bridges.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.yml' ) }}"
  when: not(result_output.endswith('.csv'))
  register: result_out

- name: Export Result
  debug:
    msg: "{{ result_out }}}}"

- name: CSV Export {{ output_object }}
  template:
    src: "bridges-csv.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.csv' ) }}"
  when: result_output.endswith('.csv')
  register: csv_result_out

- name: CSV Export Result
  debug:
    msg: "{{ csv_result_out }}}}"