---
- name: Set Object Name
  set_fact:
    output_object: client_profiles

- name: "Get {{ output_object }}"
  solace_get_client_profiles:
    msg_vpn: "{{msg_vpn}}"
    query_params:
        where:
          - "clientProfileName!=#*"
  register: result

- name: Export {{ output_object }}
  template:
    src: "client-profiles.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.yml' ) }}"
  run_once: true
  register: result_out

- name: Export Result
  debug:
    msg: "{{ result_out }}}}"