---
- name: Set Object Name
  set_fact:
    output_object: rdps

- name: "Get {{ output_object }}"
  solace_get_rdps:
    msg_vpn: "{{msg_vpn}}"
  register: result

- name: "Get Queue Bindings"
  solace_get_rdp_queue_bindings:
    msg_vpn: "{{msg_vpn}}"
    rdp_name: "{{item.data.restDeliveryPointName}}"
  loop: "{{ result.result_list }}"
  register: rdp_queue_bindings

- name: "Get REST Consumers"
  solace_get_rdp_rest_consumers:
    msg_vpn: "{{msg_vpn}}"
    rdp_name: "{{item.data.restDeliveryPointName}}"
  loop: "{{ result.result_list }}"
  register: rdp_rest_consumers

- name: Export {{ output_object }}
  template:
    src: "rdps.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.yml' ) }}"
  run_once: true
  register: result_out

- name: Export Result
  debug:
    msg: "{{ result_out }}}}"