---
- name: Set Object Name
  set_fact:
    output_object: rdps

- name: "Get {{ output_object }}"
  solace_get_rdps:
    msg_vpn: "{{msg_vpn}}"
  register: result

- name: "Get Queue Bindings"
  solace_get_rdp_queue_bindings:
    msg_vpn: "{{msg_vpn}}"
    rdp_name: "{{item.data.restDeliveryPointName}}"
  loop: "{{ result.result_list | rejectattr('data', '==',{}) }}"
  register: rdp_queue_bindings

- name: "Get REST Consumers"
  solace_get_rdp_rest_consumers:
    msg_vpn: "{{msg_vpn}}"
    rdp_name: "{{item.data.restDeliveryPointName}}"
  loop: "{{ result.result_list | rejectattr('data', '==',{}) }}"
  register: rdp_rest_consumers

- name: Export {{ output_object }}
  template:
    src: "rdps.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.yml' ) }}"
  when: not(result_output.endswith('.csv'))
  register: result_out

- name: Export Result
  debug:
    msg: "{{ result_out }}}}"

- name: CSV Export {{ output_object }}
  template:
    src: "rdps-csv.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.csv' ) }}"
  when: result_output.endswith('.csv')
  register: csv_result_out

- name: CSV Export Result
  debug:
    msg: "{{ csv_result_out }}}}"