---
- name: Set Object Name
  set_fact:
    output_object: jndi_cfs

- name: "Get {{ output_object }}"
  solace_get_jndi_connection_factories:
    msg_vpn: "{{msg_vpn}}"
    query_params:
      where:
      - "connectionFactoryName=={{ search_filter | default('*')}}"
  register: result

- name: Export {{ output_object }}
  template:
    src: "jndi-cfs.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.yml' ) }}"
  when: not(result_output.endswith('.csv'))
  register: result_out

- name: Export Result
  debug:
    msg: "{{ result_out }}}}"

- name: CSV Export {{ output_object }}
  template:
    src: "result-csv.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.csv' ) }}"
  when: result_output.endswith('.csv')
  register: csv_result_out

- name: CSV Export Result
  debug:
    msg: "{{ csv_result_out }}}}"