---
- name: Set Object Name
  set_fact:
    output_object: queues

- name: "Get {{ output_object }}"
  solace_get_queues:
    msg_vpn: "{{msg_vpn}}"
    query_params:
        where:
          - "queueName!=#*"
  register: result

- name: "Get Queue Subscriptions"
  solace_get_queue_subscriptions:
    msg_vpn: "{{msg_vpn}}"
    queue_name: "{{item.data.queueName}}"
  when: result.result_list is defined
  loop: "{{ result.result_list | rejectattr('data', '==',{}) | list }}"
  register: queue_subscriptions

# - name: Debug Queue Subscriptions
#   debug:
#     msg: "{{ queue_subscriptions }}"

- name: Export {{ output_object }}
  template:
    src: "queues.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.yml' ) }}"
  when: not(result_output.endswith('.csv'))
  register: result_out

- name: Export Result
  debug:
    msg: "{{ result_out }}}}"

- name: CSV Export {{ output_object }}
  template:
    src: "queues-csv.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.csv' ) }}"
  when: result_output.endswith('.csv')
  register: csv_result_out

- name: CSV Export Result
  debug:
    msg: "{{ csv_result_out }}}}"