---
- name: Set Object Name
  set_fact:
    output_object: mqtt_sessions

- name: "Get {{ output_object }}"
  solace_get_mqtt_sessions:
    msg_vpn: "{{msg_vpn}}"
    query_params:
      where:
      - "mqttSessionClientId=={{ search_filter | default('*')}}"
  register: result

- name: "Get {{ output_object }} Subscriptions"
  solace_get_mqtt_session_subscriptions:
    msg_vpn: "{{msg_vpn}}"
    client_id: "{{item.data.mqttSessionClientId}}"
  loop: "{{ result.result_list }}"
  register: mqtt_session_subscriptions

- name: Export {{ output_object }}
  template:
    src: "mqtt-sessions.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.yml' ) }}"
  when: not(result_output.endswith('.csv'))
  register: result_out

- name: Export Result
  debug:
    msg: "{{ result_out }}}}"

- name: CSV Export {{ output_object }}
  template:
    src: "mqtt-sessions-csv.j2"
    dest: "{{ result_output | default('../output/get-'+ output_object +'_result.csv' ) }}"
  when: result_output.endswith('.csv')
  register: csv_result_out

- name: CSV Export Result
  debug:
    msg: "{{ csv_result_out }}}}"