---
- name: Import CSV Playbook
  hosts: "localhost"
  connection: local
  gather_facts: no
  any_errors_fatal: true
  pre_tasks:
    - set_fact:
        csv_file: 
        template_file: 
        output_file: 
  roles:
  - role: import-csv
